project:
  type: book
  output-dir: _output

profile:
  default: es
  group:
    - [es, en]

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  pdf:
    documentclass: scrbook
    toc: true
    number-sections: true
    colorlinks: true
